[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/newlp/"
  status = 301

[[redirects]]
  from = "/newlp/*"
  to = "/newlp/:splat"
  status = 200

[[redirects]]
  from = "/uitools/*"
  to = "/uitools/:splat"
  status = 200